### ISSUE TITLE
[Feature Request] Export Application To Template

### ISSUE THREAD

**Issue by cybertza** [SelfhostedPro/Shipwright#2]
Just as an idea to increase your template library, you could potentially create a way to export an running Application to yaml/json

(both for easy backup if you need to change a setting and also to quickly and easily increase your template DB)

Would also be very nice to be able to import txt based templates as opposed to just the download button, but i am a first time user, this overall the easiest docker adding web interface i've used.

Keep up the good work

**Comment by cybertza** [comment]
Awesome, thanks, was able to create a yaml file with a bit of tinkering, Will beautify it when the GUI editor is running, small things like port names and so are evading me in yaml. But the rest seems to be working well.

https://github.com/cybertza/yacht-zoneminder

Did it like that for now.
Thanks again

**Comment by SelfhostedPro** [comment]
Added a pull request to add port labels here: https://github.com/cybertza/yacht-zoneminder/pull/2

If you have any more trouble, let me know and I'm happy to answer questions.
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SelfhostedPro** [comment]
This is now available here: https://shipwright.yacht.sh/
